POST http://localhost:8080/cadastrar
Content-Type: application/json

{
   "name": "Nome Fictício",
   "email": "email13340@example.com",
   "password": "senha_secreta",
   "cep": "12345-678",
   "uf": "UF",
   "city": "Cidade Fictícia"
}

### Login

POST http://localhost:8080/logar
Content-Type: application/json

{
   "email": "email130@example.com",
   "password": "senha_secreta"
}

### Atualizar um usuario

PUT http://localhost:8080/atualizar
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIwNTlkMjQ5Mi04YzhlLTQxYzktOGFjZi1lOTU3MjAyMzYxYmUiLCJpYXQiOjE2OTgwODI1NDQsImV4cCI6MTY5ODA4NjE0NH0.ig546ueNbndNoCYpzQioZnY4t6KsGKer62KD1nB3C-4
Content-Type: application/json

{
   "email": "email14@example.com",
   "password": "senha_secreta",
   "cep": "876-54321",
   "uf": "FU",
   "city": "E verdade"
}

### Excluir um usuario

DELETE http://localhost:8080/excluir
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI3NDNkOGI4Mi00YzUxLTQ2YjAtOWI3Yy03OGIzNjFkMjFjOWUiLCJpYXQiOjE2OTc2NTExMDEsImV4cCI6MTY5NzY1NDcwMX0.Q_NYzOmVXP2cW4JItII4mqBKhN_5Ym1eztGdghAJL58
Content-Type: application/json

{
   "email": "email14@example.com",
   "password": "senha_secreta"
}


### Lista todos os produtos

GET http://localhost:8080/listar
Content-Type: application/json

### Registra um produto

POST http://localhost:8080/registrar
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIwNTlkMjQ5Mi04YzhlLTQxYzktOGFjZi1lOTU3MjAyMzYxYmUiLCJpYXQiOjE2OTgwODI1NDQsImV4cCI6MTY5ODA4NjE0NH0.ig546ueNbndNoCYpzQioZnY4t6KsGKer62KD1nB3C-4
Content-Type: application/json

{
  "name": "Nike",
  "description": "Tênis ",
  "categories_id": 4,
  "mark": "Nike",
  "price": "300000",
  "quantity": 200
}

### Atualiza um produto

PUT http://localhost:8080/atualizarProduto
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIwNTlkMjQ5Mi04YzhlLTQxYzktOGFjZi1lOTU3MjAyMzYxYmUiLCJpYXQiOjE2OTgwODc3OTQsImV4cCI6MTY5ODA5MTM5NH0.vTPRzivnN4JHxMluHjP7eT2TvO5jNYhfmPeq0-FQnpU
Content-Type: application/json

{
  "id": "2ffd22e3-f52c-40e2-af75-50195ddd5648",
  "name": "Nike Vomero 17",
  "description": "Tenis Griff",
  "categories_id": 2,
  "mark": "Nike",
  "price": "259000"
}

### Deleta um produto

DELETE http://localhost:8080/excluirProduto/a40ccebf-8c1d-4d05-a58d-6b0d62c75de1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIwNTlkMjQ5Mi04YzhlLTQxYzktOGFjZi1lOTU3MjAyMzYxYmUiLCJpYXQiOjE2OTgwODc3OTQsImV4cCI6MTY5ODA5MTM5NH0.vTPRzivnN4JHxMluHjP7eT2TvO5jNYhfmPeq0-FQnpU
Content-Type: application/json


### Registra uma compra.


POST http://localhost:8080/venda
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIwNTlkMjQ5Mi04YzhlLTQxYzktOGFjZi1lOTU3MjAyMzYxYmUiLCJpYXQiOjE2OTgwODY4MTYsImV4cCI6MTY5ODA5MDQxNn0.Y8ZFPVdvWO3-Bc0NscybZMGk6BKG6EvkR38sD7lshXQ
Content-Type: application/json

{
  "product_id": "2ffd22e3-f52c-40e2-af75-50195ddd5648",
  "quantity": 50,
  "form_of_payment": "credito",
  "card": {
    "number": "4242424242424242",
    "exp_month": 12,
    "exp_year": 2029,
    "cvc": 123
  }
}

### Lista todas as vendas

GET http://localhost:8080/vendas
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIwNTlkMjQ5Mi04YzhlLTQxYzktOGFjZi1lOTU3MjAyMzYxYmUiLCJpYXQiOjE2OTgwODY4MTYsImV4cCI6MTY5ODA5MDQxNn0.Y8ZFPVdvWO3-Bc0NscybZMGk6BKG6EvkR38sD7lshXQ
Content-Type: application/json


### Lista venda por  id

GET http://localhost:8080/vendas/114741a0-83cd-4ec3-9579-ca500012b32a
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIwNTlkMjQ5Mi04YzhlLTQxYzktOGFjZi1lOTU3MjAyMzYxYmUiLCJpYXQiOjE2OTgwODI1NDQsImV4cCI6MTY5ODA4NjE0NH0.ig546ueNbndNoCYpzQioZnY4t6KsGKer62KD1nB3C-4
Content-Type: application/json


### listar estoque

GET http://localhost:8080/listarEstoque
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIwNTlkMjQ5Mi04YzhlLTQxYzktOGFjZi1lOTU3MjAyMzYxYmUiLCJpYXQiOjE2OTgwODI1NDQsImV4cCI6MTY5ODA4NjE0NH0.ig546ueNbndNoCYpzQioZnY4t6KsGKer62KD1nB3C-4
Content-Type: application/json


### delete  um item do estoque

DELETE http://localhost:8080/deletarEstoque/114741a0-83cd-4ec3-9579-ca500012b32a
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIwNTlkMjQ5Mi04YzhlLTQxYzktOGFjZi1lOTU3MjAyMzYxYmUiLCJpYXQiOjE2OTgwODI1NDQsImV4cCI6MTY5ODA4NjE0NH0.ig546ueNbndNoCYpzQioZnY4t6KsGKer62KD1nB3C-4
Content-Type: application/json


### Atualizar estoque

PUT http://localhost:8080/atualizarEstoque/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIwNTlkMjQ5Mi04YzhlLTQxYzktOGFjZi1lOTU3MjAyMzYxYmUiLCJpYXQiOjE2OTgwODI1NDQsImV4cCI6MTY5ODA4NjE0NH0.ig546ueNbndNoCYpzQioZnY4t6KsGKer62KD1nB3C-4
Content-Type: application/json

{
  "productId":"114741a0-83cd-4ec3-9579-ca500012b32a",
  "quantity": "100"
}


### listar categorias

GET http://localhost:8080/listarCategorias
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIwNTlkMjQ5Mi04YzhlLTQxYzktOGFjZi1lOTU3MjAyMzYxYmUiLCJpYXQiOjE2OTgwODI1NDQsImV4cCI6MTY5ODA4NjE0NH0.ig546ueNbndNoCYpzQioZnY4t6KsGKer62KD1nB3C-4

###

POST http://localhost:8080/cadastrarCategorias
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIwNTlkMjQ5Mi04YzhlLTQxYzktOGFjZi1lOTU3MjAyMzYxYmUiLCJpYXQiOjE2OTgwODI1NDQsImV4cCI6MTY5ODA4NjE0NH0.ig546ueNbndNoCYpzQioZnY4t6KsGKer62KD1nB3C-4
Content-Type: application/json

{
  "name": "esportivos",
  "description": "artigos esportivos como: luvas, pé de pato, oculos de natação..."
}

###
###
### Carrinho de compras

POST http://localhost:8080/carrinho/addItem
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIwNTlkMjQ5Mi04YzhlLTQxYzktOGFjZi1lOTU3MjAyMzYxYmUiLCJpYXQiOjE2OTgwMTIwMjIsImV4cCI6MTY5ODAxNTYyMn0.gYqV8DeFbqyF_dKbRbZBNilzP6H-ioigsv_DnEjMdVA
Content-Type: application/json

{
  "product_id": "114741a0-83cd-4ec3-9579-ca500012b32a",
  "name": "nome do produto",
  "price": 2000,
  "quantity": 15
}

###

GET http://localhost:8080/carrinho/listar
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIwNTlkMjQ5Mi04YzhlLTQxYzktOGFjZi1lOTU3MjAyMzYxYmUiLCJpYXQiOjE2OTgwMTIwMjIsImV4cCI6MTY5ODAxNTYyMn0.gYqV8DeFbqyF_dKbRbZBNilzP6H-ioigsv_DnEjMdVA
Content-Type: application/json

###

DELETE http://localhost:8080/carrinho/removerItem/114741a0-83cd-4ec3-9579-ca500012b32a
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIwNTlkMjQ5Mi04YzhlLTQxYzktOGFjZi1lOTU3MjAyMzYxYmUiLCJpYXQiOjE2OTgwMTIwMjIsImV4cCI6MTY5ODAxNTYyMn0.gYqV8DeFbqyF_dKbRbZBNilzP6H-ioigsv_DnEjMdVA
Content-Type: application/json

###

PUT http://localhost:8080/carrinho/atualizarQuantidade
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIwNTlkMjQ5Mi04YzhlLTQxYzktOGFjZi1lOTU3MjAyMzYxYmUiLCJpYXQiOjE2OTgwMTIwMjIsImV4cCI6MTY5ODAxNTYyMn0.gYqV8DeFbqyF_dKbRbZBNilzP6H-ioigsv_DnEjMdVA
Content-Type: application/json

{
  "product_id": "114741a0-83cd-4ec3-9579-ca500012b32a",
  "quantity": 5
}

###

GET http://localhost:8080/carrinho/total
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIwNTlkMjQ5Mi04YzhlLTQxYzktOGFjZi1lOTU3MjAyMzYxYmUiLCJpYXQiOjE2OTgwMTYyMTIsImV4cCI6MTY5ODAxOTgxMn0.-y05AUEO52G2dWC_Ely7UnReM4ZusdjHkONaJSi9opM
Content-Type: application/json


###

